global:
  scrape_interval: 15s
  scrape_timeout: 15s

  query_log_file: query_log_file.log

scrape_configs:
  - job_name: "spring-actuator"
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ["host.docker.internal:8080"]