server:
  servlet:
    session:
      timeout: 54000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:53306/culture_ticketing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: com.culture.ticketing.common.infra.MySQL8DialectCustom

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  redis:
    host: localhost
    port: 16379
    password: 1234

logging:
  level:
    org.hibernate.SQL: debug